language: node_js
node_js:
  - "10"
  - "11"

addons:
  code_climate:
    repo_token: b4ef7769e0f8f04456e8e1168b4beb44561bd5ce9ca216458a164e19c4cf7308

branches:
  only:
    - master

cache: yarn

install:
  - yarn install --ignore-engines
  - yarn lint
  - yarn test

script:
  - yarn build

after_success:
  - yarn travis-deploy-once "npm run codeclimate && npm run semantic-release"

notifications:
  email: false
