environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

test_script:
  - node --version
  - npm --version
  - yarn --version
  - yarn test

build: off
